import Foundation

@Observable
@MainActor
class DrillsService {
    var allDrills: [Drill] = []

    func loadDrills(for position: PlayerPosition, weakness: WeaknessArea, skillLevel: SkillLevel) {
        allDrills = generateDrills(for: position, weakness: weakness, level: skillLevel)
    }

    func filteredDrills(weakestSkills: [SkillCategory]) -> [Drill] {
        guard !weakestSkills.isEmpty else { return allDrills }
        let weakNames = Set(weakestSkills.map(\.rawValue))
        let filtered = allDrills.filter { weakNames.contains($0.targetSkill) }
        return filtered.isEmpty ? allDrills : filtered
    }

    private func generateDrills(for position: PlayerPosition, weakness: WeaknessArea, level: SkillLevel) -> [Drill] {
        var drills: [Drill] = []

        let skills = position.skills
        for skill in skills {
            drills.append(contentsOf: drillsForSkill(skill, level: level))
        }

        let weaknessDrills = drillsForWeakness(weakness, level: level)
        drills.append(contentsOf: weaknessDrills)

        return drills
    }

    private func drillsForSkill(_ skill: SkillCategory, level: SkillLevel) -> [Drill] {
        let diff = difficultyFor(level)
        switch skill {
        case .firstTouch:
            return [
                Drill(name: "Wall Pass Returns", description: "Pass against a wall and control the return with different surfaces of your foot. Focus on cushioning the ball.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Soft touch on reception", "Get body behind the ball", "Use inside and outside of foot"], reps: "3 sets of 20"),
                Drill(name: "Aerial Control Circuit", description: "Toss the ball in the air, control with thigh, then foot, then pass. Alternate between left and right.", duration: "12 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Watch the ball all the way", "Cushion on contact", "Keep balanced stance"], reps: "3 sets of 15"),
                Drill(name: "Bounce & Settle", description: "Drop the ball from waist height onto the ground. As it bounces, kill it dead with the sole of your foot. Progress to letting it bounce twice.", duration: "8 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Hover foot just above the ball", "Absorb energy on contact", "Alternate feet every 5 reps"], reps: "4 sets of 12"),
                Drill(name: "Driven Pass Reception", description: "Have a partner hit hard, driven passes along the ground. Receive and redirect in one motion to a target cone.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Open body to receive", "Soft ankle on contact", "Direct ball into space, not back to passer"], reps: "3 sets of 10"),
                Drill(name: "1 Touch Wall Pass at 3 Yards", description: "Stand 3 yards from a wall and pass the ball along the ground using 1 touch whenever possible. Mostly inside of feet. Wall returns the ball for continuous reps.", duration: "8 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Soft touch on each pass", "Alternate feet where possible", "Keep the ball on the ground"], reps: "50 passes"),
                Drill(name: "2 Touch Wall Pass at 5 Yards", description: "Stand 5 yards from wall. Control the return with your first touch then pass back with your second touch. Mostly inside of feet.", duration: "8 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["First touch out of your feet", "Quick second touch pass", "Stay on your toes"], reps: "25 passes"),
                Drill(name: "1 Touch Wall Pass at 5 Yards", description: "Same as 3-yard drill but from 5 yards. The ball comes back faster requiring quicker reactions and sharper touch.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Get body behind the ball early", "Cushion on contact", "Immediate return pass"], reps: "50 passes"),
                Drill(name: "Weak Foot Wall Pass at 5 Yards", description: "Stand 5 yards from wall. Every pass must be made with your non-preferred foot. Receiving foot can be either — but every pass back must be weak foot.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Lock ankle on weak foot pass", "Commit fully to the technique", "Accuracy over power"], reps: "25 passes"),
                Drill(name: "1 Touch Wall Pass at 10 Yards", description: "Stand 10 yards from wall. Pass with 1 touch. Ball returns faster requiring sharper reactions and cleaner first touch.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Early body positioning before ball arrives", "Soft cushioned touch", "Return pass with weight and accuracy"], reps: "50 passes"),
                Drill(name: "2 Touch Wall Pass at 10 Yards", description: "Stand 10 yards from wall. Control the return then pass back in 2 touches.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["First touch sets up the pass", "Second touch is the pass", "Stay balanced throughout"], reps: "25 passes"),
                Drill(name: "Weak Foot Wall Pass at 10 Yards", description: "Same as weak foot drill at 5 yards but from 10 yards. Passing with non-preferred foot at greater distance.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Strike through the center of the ball", "Follow through toward the wall", "Build confidence with each rep"], reps: "25 passes"),
                Drill(name: "Alternating Foot Wall Pass at 10 Yards", description: "Stand 10 yards from wall. Must alternate receiving and passing foot on every touch. A sweep touch is required to redirect.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Commit to alternating feet every rep", "Sweep touch for the redirect", "Build a smooth rhythm"], reps: "25 passes"),
                Drill(name: "Move In and Out Wall Drill", description: "Start 10 yards from wall. Pass with 1 touch and take a step closer after each pass until you can touch the wall. Reverse — step back with each pass until 10 yards away.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Adjust touch weight as distance changes", "Stay balanced at each position", "One full in-and-out cycle counts as 1 rep"], reps: "3 complete cycles"),
                Drill(name: "1 Touch Wall Pass at 20 Yards", description: "Stand 20 yards from wall. Pass with 1 touch. Some instep striking required to reach the wall. Receiving the powerful return cleanly is the key challenge.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Strike with instep for distance", "Get body behind the ball on return", "First touch sets up your next action"], reps: "25 passes"),
                Drill(name: "Loft and Control at 25 Yards", description: "Stand 25 yards from wall. Drive ball off wall hitting it 5 to 8 feet from the ground on the fly. Receive the return cleanly and repeat. Alternate feet.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Drive with instep for height and distance", "Watch ball all the way down", "Settle cleanly before next pass"], reps: "15 passes"),
                Drill(name: "Track It Down Drill", description: "Stand 8 yards from wall. Toss ball high off wall so it returns overhead. Sprint after it, control it, turn, then strike against wall and receive again.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Sprint immediately after the toss", "Control before you turn", "Clean strike to restart the sequence"], reps: "15 tosses"),
                Drill(name: "Chest Trap and Pass Wall Drill", description: "Stand 10 yards from wall. Toss ball so it returns at chest level. Chest trap to receive, control to feet, then pass against wall and receive again.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Cushion with chest on contact", "Drop ball to feet cleanly", "Quick pass after control"], reps: "15 tosses"),
                Drill(name: "Turn Left and Return", description: "Stand 10 yards from wall with 2 cones placed diagonally behind you 20 yards away. Play ball off wall along the ground. Receive rebound and make a 120-degree turn to the left. Dribble around cone and return to start.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Receive with a soft touch", "Commit to the turn direction", "Accelerate away from the wall after the turn"], reps: "10 turns"),
                Drill(name: "Turn Right and Return", description: "Same as Turn Left drill except turn to the right after receiving from the wall.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Turn sharply to the right", "Ball stays close through the turn", "Sprint back to starting position"], reps: "10 turns"),
                Drill(name: "1 Touch and Spin Wall Drill", description: "Stand 10 yards from wall. Pass with 1 touch then immediately spin 360 degrees. Be ready to receive the return after the spin. Alternate spin direction each rep.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Quick full spin", "Locate the ball as you come out of the spin", "Immediate touch on return"], reps: "20 passes")
            ]
        case .bodyPosition:
            return [
                Drill(name: "Shadow Play Positioning", description: "Move through cones mimicking game situations. Focus on body orientation, open hips, and scanning.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Open body to the field", "Check shoulders constantly", "Stay on toes"], reps: "4 sets of 2 min"),
                Drill(name: "Mirror Drill", description: "Partner mirrors your movements. Stay low, balanced, and ready to react in any direction.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Low center of gravity", "Quick feet", "Eyes on partner's hips"], reps: "5 rounds of 30 sec"),
                Drill(name: "Receive & Turn Pressure", description: "Set up 4 cones in a square. Receive a pass, check your shoulder, then turn toward the open cone. A passive defender applies light pressure.", duration: "12 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Check shoulder before the ball arrives", "Open hips to escape route", "First touch sets up the turn"], reps: "4 sets of 6"),
                Drill(name: "Scanning Frequency Drill", description: "Receive passes in a grid. A coach holds up colored cones—you must call the color before receiving. Builds the habit of scanning.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Scan before, during, and after receiving", "Keep head on a swivel", "Body open to see both ball and field"], reps: "3 sets of 2 min"),
                Drill(name: "Inside Foot Chop Turn", description: "Dribble into space and chop down on the ball with the inside of the foot taking it away in the opposite direction. Use 2 chops with same foot or push away with outside of other foot. Slow in, fast out.", duration: "8 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Chop through the ball firmly", "Low body position through the turn", "Accelerate immediately after"], reps: "10 turns each direction"),
                Drill(name: "Outside Foot Chop Turn", description: "Same as inside chop turn but use the outside of the foot — little toe side. Chop the ball away in the same direction as the chopping foot.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Outside of foot contacts ball firmly", "Quick body adjustment after chop", "Eyes up after the turn"], reps: "10 turns each direction"),
                Drill(name: "Sole Stop Turn", description: "With the ball rolling toward you, stop it dead with the sole of your foot, let your body run over the ball, then play it back in the opposite direction.", duration: "8 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Cushion to stop — not stamp", "Run over the ball smoothly", "Drive away in new direction immediately"], reps: "10 turns"),
                Drill(name: "Pull Back Turn", description: "Pull the ball back with one foot while pivoting and push the ball with the same foot into new space.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Pull then push with same foot", "Turn hips with the ball", "Explode out of the turn"], reps: "10 turns each foot"),
                Drill(name: "Instep Fake Behind-Leg Turn", description: "Fake a kick with your instep, then reach forward and chop the front side of the ball behind your standing leg. Requires hip rotation and deception.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Convincing fake motion first", "Reach ball cleanly behind standing leg", "Immediate acceleration after the turn"], reps: "8 turns each direction"),
                Drill(name: "Stepover Turn", description: "Step over the ball with one foot faking an inside pass, then take the ball away with the outside of that same foot. Or spin and use the other foot.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Stepover must be convincing", "Quick take away with outside of foot", "Accelerate immediately after"], reps: "8 turns each direction")
            ]
        case .ballControl:
            return [
                Drill(name: "Cone Dribble Maze", description: "Dribble through a tight cone setup using close touches. Focus on keeping the ball within playing distance.", duration: "12 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Small touches", "Head up between cones", "Use both feet equally"], reps: "4 sets through the course"),
                Drill(name: "Tight Space Juggling", description: "Juggle inside a small square. Each time the ball leaves the square, restart the count.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Soft controlled touches", "Stay in the zone", "Use all surfaces"], reps: "Best of 5 attempts"),
                Drill(name: "Figure 8 Dribbling", description: "Set two cones 3 feet apart. Dribble in a figure-8 pattern using only the inside and outside of one foot, then switch.", duration: "10 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Ball glued to your foot", "Accelerate around the cone", "Low center of gravity"], reps: "3 sets of 1 min per foot"),
                Drill(name: "Pressure Box Keepaway", description: "In a 5x5 yard box, keep the ball away from a defender for as long as possible. Use shielding, turns, and quick changes of direction.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Use your body to shield", "Stay aware of space behind you", "Quick direction changes beat speed"], reps: "5 rounds of 45 sec"),
                Drill(name: "Foundation Touch Drill", description: "Tap ball back and forth with inside of both alternating feet in a small space. Balance perfect technique with maximum speed. Clean technique is more important than being fast.", duration: "5 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Soft inside of foot contact", "Stay on your toes", "Build speed without losing control"], reps: "50 touches"),
                Drill(name: "Toe Tap Drill", description: "Tap the top of the ball with the front half of the sole of alternating feet. Keep the ball stationary and build a quick rhythm.", duration: "5 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Light touches on top of ball", "Alternate feet evenly", "Increase tempo gradually"], reps: "40 touches"),
                Drill(name: "Rollover Drill", description: "Roll the front half of your sole over the top of the ball and advance it sideways. Switch feet each set.", duration: "5 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Roll from back to front of sole", "Keep ball moving laterally", "Stay balanced"], reps: "15 times each foot"),
                Drill(name: "Drag Back Drill", description: "Tap the top of the ball with alternating soles and pull it back a few inches with each touch. Controlled drag every rep.", duration: "5 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Use front half of sole", "Controlled pull each time", "Alternate feet smoothly"], reps: "30 times"),
                Drill(name: "Side Drag Drill", description: "Tap the top of the ball with alternating soles and pull to the side a few inches with each touch. Like Foundation Touch but with the sole.", duration: "5 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Slight lateral drag each touch", "Stay compact", "Build rhythm before adding speed"], reps: "30 times"),
                Drill(name: "Inside-Outside Touch Drill", description: "Touch ball with inside then outside of the same foot in a rhythmic step-touch fashion advancing ball forward a few inches each touch.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Inside touch then outside touch same foot", "Smooth rhythm throughout", "Advance ball gradually"], reps: "10 yards each foot"),
                Drill(name: "Outside Two Inside Two Drill", description: "Touch ball with outside of foot twice then inside of same foot twice in a step-touch rhythm advancing ball forward a few inches each touch.", duration: "8 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Two outside then two inside same foot", "Keep rhythm consistent", "Stay low and balanced"], reps: "10 yards each foot"),
                Drill(name: "Change of Pace Dribble", description: "Dribble slowly forward 10 yards with both feet then increase to maximum speed for 10 more yards using the instep with step-touch technique. Stop ball at 20 yards.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Deliberate slow phase first", "Explosive acceleration to full speed", "Push ball with instep at full pace"], reps: "5 times"),
                Drill(name: "Box Dribble Drill", description: "Dribble around the outside of a 5x5 yard box using rollovers and dragbacks on each side of the box.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Sharp corners — don't drift wide", "Ball stays close throughout", "Increase speed each lap"], reps: "4 times around"),
                Drill(name: "Figure 8 Cone Dribble", description: "Dribble in a figure 8 pattern around 2 cones 5 yards apart. Complete with either foot then isolate right and left foot separately.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Tight turns around each cone", "Accelerate between cones", "Use inside and outside of foot"], reps: "4 times — 2 with either foot, 1 right only, 1 left only"),
                Drill(name: "Cone Slalom Dribble", description: "Place 5 cones in a line 3 yards apart. Dribble in slalom to the top of the line and back.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Sharp cuts not wide arcs", "Ball stays close through each gate", "Accelerate on the straights"], reps: "4 times"),
                Drill(name: "Staircase Cone Dribble", description: "Lay out 6 cones in a staircase pattern 5 yards apart up and across. Dribble around cones following the staircase pattern.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Plan the route ahead of the ball", "Quick direction changes at each cone", "Ball always within playing distance"], reps: "4 times"),
                Drill(name: "15 Yard Loop Drill", description: "Place 4 cones in a line 5 yards apart. Dribble around the 3rd cone, back around the 2nd cone, and finish at the 4th cone.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Commit to the loop path", "Accelerate out of each turn", "Stay in control through the full pattern"], reps: "4 times"),
                Drill(name: "180 Turn Dribble Drill", description: "Dribble 5 yards then make a sharp 180-degree turn. Dribble 5 yards back and repeat the turn. Complete 6 total turns all with the same foot then switch.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Sharp turn — don't drift wide", "Accelerate immediately after the turn", "Use inside hook or pullback turn"], reps: "1 set each foot"),
                Drill(name: "Start-Stop Dribble Drill", description: "Dribble forward 10 yards then perform a sudden stop using the sole. Continue forward 10 yards and stop again. Alternate the stopping foot each rep.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Clean stop with sole of foot", "Immediate restart after each stop", "Simulates evading a press"], reps: "3 stops each direction"),
                Drill(name: "Sprint Dribble and Stop", description: "Sprint-dribble to a marker 25 yards away, stop the ball cleanly, sprint back to start, sprint forward to the ball, collect it and sprint-dribble back to start.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Full sprint on every phase", "Clean stop at the marker", "Collect the ball smoothly on return"], reps: "3 times")
            ]
        case .shooting:
            return [
                Drill(name: "Finishing Circuit", description: "Set up 5 shooting positions around the box. Take 3 shots from each position, focusing on technique over power.", duration: "20 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Plant foot pointing at target", "Strike through the ball", "Follow through toward goal"], reps: "15 total shots"),
                Drill(name: "One-Touch Finishes", description: "Have a partner feed balls across the box. One touch to finish. Vary the angle and speed of feeds.", duration: "15 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Quick assessment of keeper position", "Redirect with purpose", "Stay composed"], reps: "3 sets of 8"),
                Drill(name: "Driven Shot Technique", description: "Place the ball 20 yards out. Focus on striking clean through the center of the ball with your laces. Aim low corners.", duration: "15 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Lock ankle, toe down", "Lean slightly over the ball", "Hit the center-bottom of the ball"], reps: "4 sets of 5"),
                Drill(name: "Turn & Shoot", description: "Receive a pass with your back to goal, take a touch to create space, and shoot within 2 seconds. Simulates real game urgency.", duration: "15 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Quick first touch to shooting position", "Pick your spot before turning", "Shoot early—don't overthink"], reps: "3 sets of 6"),
                Drill(name: "Shooting Technique Wall Drill", description: "Stand 10 to 12 yards from a solid wall. Strike the ball ensuring toe is pointed down, knee over ball, center of instep strikes center of ball, all power from quick snapping lower leg motion.", duration: "10 min", difficulty: .beginner, targetSkill: skill.rawValue, coachingCues: ["Toe down — lock the ankle", "Knee over the ball", "Quick snap of lower leg through the ball"], reps: "30 strikes"),
                Drill(name: "First-Time Power Shooting", description: "Stand 20 yards from wall. Strike ball as hard as possible regardless of how it returns — any height, any pace, any angle. Pick a spot on the wall and keep ball low.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Read the return early", "Commit to the shot every time", "Keep ball low on the wall"], reps: "30 shots"),
                Drill(name: "Trap and Shoot Wall Drill", description: "From 20 yards, strike the wall, trap the return cleanly, and fire another shot immediately. A sound clean trap followed by a quick hard shot is the goal.", duration: "12 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["First touch sets up the shot", "Shoot within 2 touches", "Trap cleanly even when tired"], reps: "30 reps"),
                Drill(name: "Target Striking Drill", description: "Mark a 2x2 yard target on a wall with chalk. Stand 20 yards away and drive ball against wall using 2 touches each time. Track hits vs misses. Goal is 3 consecutive hits before 4 misses.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Pick your spot before striking", "Strike through the center of the ball", "Accuracy over power"], reps: "10 attempts per round"),
                Drill(name: "Wall Pass and Redirect Shooting", description: "Place 3 cones — 2 outer cones 20 yards apart and 12 yards from wall, 1 middle cone 5 yards from wall. Dribble from an outer cone toward wall, execute a wall pass around the middle cone, dribble to and around the outer cone. Repeat opposite direction.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Time the wall pass precisely", "Dribble at pace not flat out", "Finish each rep cleanly around the cone"], reps: "8 wall passes each direction")
            ]
        case .movement:
            return [
                Drill(name: "Agility Ladder Combos", description: "Run through an agility ladder with varied footwork patterns. Finish each set with a sprint.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Quick feet, light contact", "Arms drive movement", "Explode out of the ladder"], reps: "6 ladder runs"),
                Drill(name: "Check-Away Runs", description: "Practice checking to the ball then spinning away into space. Simulate creating separation from a defender.", duration: "12 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Sharp change of direction", "Accelerate after the turn", "Communicate with passer"], reps: "4 sets of 5 runs"),
                Drill(name: "Lateral Shuffle & Sprint", description: "Shuffle laterally between two cones 5 yards apart, then on a signal, explode forward in a 10-yard sprint.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Stay low during shuffle", "Push off outside foot to change direction", "Explosive first step on sprint"], reps: "4 sets of 6"),
                Drill(name: "Blindside Run Timing", description: "Start behind a cone as if behind a defender. On a visual cue, make a curved run into the box to meet a through ball.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Time the run—don't go too early", "Curve the run to stay onside", "Accelerate into the pass"], reps: "4 sets of 5 runs"),
                Drill(name: "Speed Dribble Figure 8", description: "Set 2 markers 10 to 15 yards apart. Dribble in a figure 8 using inside of feet for 6 reps then outside of feet for 6 more. As you dribble around each marker, accelerate to the next as if beating a defender.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Accelerate between markers", "Quick touches around the cone", "Use inside then outside of foot alternately"], reps: "12 total figure 8s"),
                Drill(name: "Sprint Dribble and Return", description: "Place a marker 25 yards away. Sprint-dribble to it, stop the ball cleanly, sprint backwards to start, sprint forward to the ball, collect and sprint-dribble back to start.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Full sprint on every phase", "Clean stop at the marker", "Collect ball smoothly on return sprint"], reps: "3 times"),
                Drill(name: "Aerial Collection Sprint", description: "Toss the ball high in the air. Collect with a different body part each rep — feet, thigh, or chest — then sprint away with the ball as fast as possible.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Watch ball all the way down", "Collect cleanly before sprinting", "Vary the collection surface each rep"], reps: "10 reps"),
                Drill(name: "Cone to Cone Turn Sprints", description: "Place 2 markers 7 yards apart. Sprint from one to the other using a specific turn technique at each cone. Complete 10 reps with each of 4 different turns.", duration: "12 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Commit to the turn technique each rep", "Accelerate out of every turn", "Sharp turns not wide arcs"], reps: "10 reps x 4 different turns")
            ]
        case .positioning:
            return [
                Drill(name: "Goalkeeper Angles", description: "Practice narrowing the angle by moving along the arc. Partner shoots from different positions.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Stay on your line", "Small shuffle steps", "Set before the shot"], reps: "4 sets of 6 saves"),
                Drill(name: "Cross Positioning", description: "Crosses come in from wide areas. Move to cut off the cross at the highest point. Focus on starting position and footwork.", duration: "15 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Start central, adjust based on ball position", "Take a step forward before the cross", "Claim with authority"], reps: "3 sets of 8"),
                Drill(name: "1v1 Closing Down", description: "Attacker runs at goal from different angles. Practice when to stay, when to come out, and how to set your feet.", duration: "12 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Make yourself big", "Stay on your feet as long as possible", "Force the attacker wide"], reps: "4 sets of 5")
            ]
        case .handling:
            return [
                Drill(name: "Catch and Release", description: "Partner throws balls at varying heights and speeds. Focus on clean catching and immediate distribution.", duration: "12 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["W-shape hands for high balls", "Scoop for low balls", "Secure to chest"], reps: "3 sets of 15"),
                Drill(name: "Diving Saves", description: "Partner shoots low to each side. Focus on proper diving technique—push off the near foot, hands lead, land on your side.", duration: "12 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Push off the planted foot", "Lead with hands, not body", "Get back up quickly"], reps: "3 sets of 8"),
                Drill(name: "High Ball Collection", description: "Partner or machine delivers high crosses. Practice timing your jump, catching at the highest point, and landing safely.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Take off on one foot", "Catch at highest point", "Bring knee up for protection"], reps: "3 sets of 10")
            ]
        case .distribution:
            return [
                Drill(name: "Target Passing", description: "From the goal area, distribute to targets at different distances. Alternate between throws, goal kicks, and punts.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Quick scanning", "Weight of pass", "Accurate to feet"], reps: "3 sets of 10"),
                Drill(name: "Quick Counter Throw", description: "After making a save, immediately throw to a target in a wide position. Speed of release is key.", duration: "10 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Scan before the save", "Overarm for distance, underarm for accuracy", "Hit the runner in stride"], reps: "3 sets of 8"),
                Drill(name: "Goal Kick Accuracy", description: "Place goal kicks to land in specific zones. Alternate between short and long distribution.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Consistent run-up", "Strike clean through the ball", "Aim for space, not a player"], reps: "3 sets of 6")
            ]
        case .reflexes:
            return [
                Drill(name: "Reaction Ball Saves", description: "Use a reaction ball thrown at the wall. Dive to save the unpredictable bounce.", duration: "10 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Stay in ready position", "Explosive push off", "Eyes on the ball"], reps: "4 sets of 10"),
                Drill(name: "Close-Range Rapid Fire", description: "Three shooters fire in quick succession from 8 yards. Reset position between each shot.", duration: "10 min", difficulty: .advanced, targetSkill: skill.rawValue, coachingCues: ["Get set between saves", "Stay on your toes", "React, don't guess"], reps: "3 sets of 9 shots"),
                Drill(name: "Tennis Ball Reactions", description: "Partner throws tennis balls at close range. Catch or parry. Smaller ball forces faster hand-eye coordination.", duration: "8 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Soft hands", "Track the ball all the way", "Use both hands"], reps: "4 sets of 12")
            ]
        case .communication:
            return [
                Drill(name: "Command the Box", description: "During crossing drills, practice calling for the ball, organizing defenders, and communicating early.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Loud and clear commands", "Early calls", "Use player names"], reps: "Full session"),
                Drill(name: "Set Piece Organization", description: "Walk through corners and free kicks. Practice directing defensive wall and marking assignments vocally.", duration: "15 min", difficulty: .intermediate, targetSkill: skill.rawValue, coachingCues: ["Take charge early", "Assign marks clearly", "Adjust wall position based on ball placement"], reps: "8 set pieces"),
                Drill(name: "Backline Sweeper Calls", description: "In a small-sided game, focus only on organizing the back line. Push up, hold, and squeeze commands.", duration: "15 min", difficulty: diff, targetSkill: skill.rawValue, coachingCues: ["Constant communication", "Short, sharp commands", "See the whole picture"], reps: "3 rounds of 4 min")
            ]
        }
    }

    private func drillsForWeakness(_ weakness: WeaknessArea, level: SkillLevel) -> [Drill] {
        let diff = difficultyFor(level)
        switch weakness {
        case .firstTouch:
            return [
                Drill(name: "First Touch Pressure Drill", description: "Receive passes under simulated pressure. A defender closes you down, forcing quick control and turn.", duration: "15 min", difficulty: diff, targetSkill: "First Touch", coachingCues: ["Look before receiving", "Take touch away from pressure", "Protect the ball"], reps: "4 sets of 8"),
                Drill(name: "Two-Touch Passing Triangles", description: "In a triangle of 3 players, first touch sets up a clean pass. Increase tempo every minute.", duration: "10 min", difficulty: diff, targetSkill: "First Touch", coachingCues: ["First touch out of feet", "Weight of pass matters", "Communicate early"], reps: "4 rounds of 2 min")
            ]
        case .shooting:
            return [
                Drill(name: "Shooting Under Fatigue", description: "Sprint 20 yards, receive a pass, and shoot. The fatigue simulates real game conditions.", duration: "15 min", difficulty: diff, targetSkill: "Shooting Form", coachingCues: ["Composure despite fatigue", "Pick your spot", "Follow through clean"], reps: "3 sets of 6"),
                Drill(name: "Weak Foot Finishing", description: "All shots must be taken with your weaker foot. Start close and gradually move farther from goal.", duration: "15 min", difficulty: diff, targetSkill: "Shooting Form", coachingCues: ["Lock the ankle", "Technique over power", "Aim for placement"], reps: "3 sets of 8")
            ]
        case .dribbling:
            return [
                Drill(name: "1v1 Dribble Gauntlet", description: "Dribble through 4 simulated defenders. Use feints, step-overs, and changes of pace.", duration: "15 min", difficulty: diff, targetSkill: "Ball Control", coachingCues: ["Close control near defenders", "Accelerate past them", "Use body feints"], reps: "5 runs through"),
                Drill(name: "Speed Dribble Sprints", description: "Dribble at full speed over 30 yards, keeping the ball under control. Focus on pushing the ball ahead and sprinting to it.", duration: "10 min", difficulty: diff, targetSkill: "Ball Control", coachingCues: ["Push ball 2-3 yards ahead", "Sprint to catch it", "Use laces for speed dribbling"], reps: "6 sprints")
            ]
        case .defending:
            return [
                Drill(name: "Defensive Stance Drill", description: "Practice jockeying, pressing triggers, and recovery runs against a partner with the ball.", duration: "15 min", difficulty: diff, targetSkill: "Body Position", coachingCues: ["Stay low and balanced", "Force onto weak foot", "Don't dive in"], reps: "4 sets of 2 min"),
                Drill(name: "Recovery Run & Tackle", description: "Start 5 yards behind an attacker. Sprint to recover, get goal-side, and make a clean challenge.", duration: "12 min", difficulty: diff, targetSkill: "Body Position", coachingCues: ["Sprint to get goal-side first", "Patience once recovered", "Time the tackle"], reps: "4 sets of 5")
            ]
        case .fitness:
            return [
                Drill(name: "High Intensity Interval Circuit", description: "Alternate between sprints, lateral shuffles, and recovery jogs. Finish with ball work.", duration: "20 min", difficulty: diff, targetSkill: "Movement", coachingCues: ["Max effort on sprints", "Active recovery", "Push through fatigue"], reps: "6 intervals"),
                Drill(name: "Ball-at-Feet Endurance", description: "Dribble continuously around a large area for timed intervals. Keep the ball close even when tired.", duration: "15 min", difficulty: diff, targetSkill: "Movement", coachingCues: ["Maintain ball contact even when tired", "Change pace and direction", "Simulate match fatigue"], reps: "3 sets of 4 min")
            ]
        }
    }

    private func difficultyFor(_ level: SkillLevel) -> DrillDifficulty {
        switch level {
        case .beginner: .beginner
        case .intermediate: .intermediate
        case .competitive, .semiPro: .advanced
        }
    }
}
